package Model.POJO;
// Generated 26/06/2019 07:32:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Director generated by hbm2java
 */
public class Director  implements java.io.Serializable {


     private Integer dirId;
     private String dirNombre;
     private Set peliculas = new HashSet(0);

    public Director() {
    }

	
    public Director(String dirNombre) {
        this.dirNombre = dirNombre;
    }
    public Director(String dirNombre, Set peliculas) {
       this.dirNombre = dirNombre;
       this.peliculas = peliculas;
    }
   
    public Integer getDirId() {
        return this.dirId;
    }
    
    public void setDirId(Integer dirId) {
        this.dirId = dirId;
    }
    public String getDirNombre() {
        return this.dirNombre;
    }
    
    public void setDirNombre(String dirNombre) {
        this.dirNombre = dirNombre;
    }
    public Set getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set peliculas) {
        this.peliculas = peliculas;
    }




}


