package Model.POJO;
// Generated 26/06/2019 07:32:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer genId;
     private String genNombre;
     private Set peliculas = new HashSet(0);

    public Genero() {
    }

	
    public Genero(String genNombre) {
        this.genNombre = genNombre;
    }
    public Genero(String genNombre, Set peliculas) {
       this.genNombre = genNombre;
       this.peliculas = peliculas;
    }
   
    public Integer getGenId() {
        return this.genId;
    }
    
    public void setGenId(Integer genId) {
        this.genId = genId;
    }
    public String getGenNombre() {
        return this.genNombre;
    }
    
    public void setGenNombre(String genNombre) {
        this.genNombre = genNombre;
    }
    public Set getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set peliculas) {
        this.peliculas = peliculas;
    }




}


