package Model.POJO;
// Generated 26/06/2019 07:32:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sexo generated by hbm2java
 */
public class Sexo  implements java.io.Serializable {


     private Integer sexId;
     private String sexNombre;
     private Set actors = new HashSet(0);

    public Sexo() {
    }

	
    public Sexo(String sexNombre) {
        this.sexNombre = sexNombre;
    }
    public Sexo(String sexNombre, Set actors) {
       this.sexNombre = sexNombre;
       this.actors = actors;
    }
   
    public Integer getSexId() {
        return this.sexId;
    }
    
    public void setSexId(Integer sexId) {
        this.sexId = sexId;
    }
    public String getSexNombre() {
        return this.sexNombre;
    }
    
    public void setSexNombre(String sexNombre) {
        this.sexNombre = sexNombre;
    }
    public Set getActors() {
        return this.actors;
    }
    
    public void setActors(Set actors) {
        this.actors = actors;
    }




}


