package Model.POJO;
// Generated 26/06/2019 07:32:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio  implements java.io.Serializable {


     private Integer socId;
     private String socCedula;
     private String socNombre;
     private String socDireccion;
     private String socTelefono;
     private String socCorreo;
     private Set alquilers = new HashSet(0);

    public Socio() {
    }

	
    public Socio(String socCedula, String socNombre, String socDireccion, String socTelefono, String socCorreo) {
        this.socCedula = socCedula;
        this.socNombre = socNombre;
        this.socDireccion = socDireccion;
        this.socTelefono = socTelefono;
        this.socCorreo = socCorreo;
    }
    public Socio(String socCedula, String socNombre, String socDireccion, String socTelefono, String socCorreo, Set alquilers) {
       this.socCedula = socCedula;
       this.socNombre = socNombre;
       this.socDireccion = socDireccion;
       this.socTelefono = socTelefono;
       this.socCorreo = socCorreo;
       this.alquilers = alquilers;
    }
   
    public Integer getSocId() {
        return this.socId;
    }
    
    public void setSocId(Integer socId) {
        this.socId = socId;
    }
    public String getSocCedula() {
        return this.socCedula;
    }
    
    public void setSocCedula(String socCedula) {
        this.socCedula = socCedula;
    }
    public String getSocNombre() {
        return this.socNombre;
    }
    
    public void setSocNombre(String socNombre) {
        this.socNombre = socNombre;
    }
    public String getSocDireccion() {
        return this.socDireccion;
    }
    
    public void setSocDireccion(String socDireccion) {
        this.socDireccion = socDireccion;
    }
    public String getSocTelefono() {
        return this.socTelefono;
    }
    
    public void setSocTelefono(String socTelefono) {
        this.socTelefono = socTelefono;
    }
    public String getSocCorreo() {
        return this.socCorreo;
    }
    
    public void setSocCorreo(String socCorreo) {
        this.socCorreo = socCorreo;
    }
    public Set getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set alquilers) {
        this.alquilers = alquilers;
    }




}


